[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 10

decorations = "None"

opacity = 0.75
# blur = true

[font]
normal.family = "Hack Nerd Font"

# Catppuccin

[colors.primary]
background = "#171421"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#241f31"
red = "#c01c28"
green = "#26a269"
yellow = "#a2734c"
blue = "#12488b"
magenta = "#a347ba"
cyan = "#2aa1b3"
white = "#d0cfcc"

[colors.bright]
black = "#5e5c64"
red = "#F66151"
green = "#33DA7A"
yellow = "#E9AD0C"
blue = "#2A7BDE"
magenta = "#C061CB"
cyan = "#33C7DE"
white = "#FFFFFF"

[colors.dim]
black = "#241f31"
red = "#c01c28"
green = "#26a269"
yellow = "#a2734c"
blue = "#12488b"
magenta = "#a347ba"
cyan = "#2aa1b3"
white = "#d0cfcc"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
